/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lecturer;

import Auth.StudentInstance;
import DBConn.DB;
import javax.swing.JFrame;
import java.sql.ResultSet;
import Alerts.Failed_Alert;

/**
 *
 * @author USER
 */
public class lecturer_see_eligibility extends javax.swing.JFrame {

    /**
     * Creates new form lecturer_see_eligibility
     */
    public lecturer_see_eligibility() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        finalout = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        subid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 64)); // NOI18N
        jLabel1.setText("Subject Eligibility");

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        finalout.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalout)
                .addGap(258, 258, 258))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(finalout)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel3.setText("Enter Subject ID");

        jButton1.setBackground(new java.awt.Color(76, 159, 255));
        jButton1.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        subid.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        subid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addComponent(subid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Go Back.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        lecturer_view_StudentProfile ViewSprofile = new lecturer_view_StudentProfile();
        ViewSprofile.show();
        dispose();
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DB db = new DB();
        db.getconnect();

        StudentInstance studentinstance = StudentInstance.getInstance();
        String user = studentinstance.getUsername();
        //        String user = "TG/2020/005";
        System.out.println(user);

        String subjectid = subid.getText();
        System.out.println(subjectid);
        try {

            if(subjectid.equals("ICT1113")){

                String sql1="Select attendance from attendance_2023_ICT1113 where s_id='"+user+"'AND (type='Theory' OR type='Practical')";
                System.out.println(sql1);
                ResultSet res1T = db.stm.executeQuery(sql1);
                double attendance1 = 0;

                while(res1T.next()){
                    Double attendence1 = res1T.getDouble("attendance");

                    System.out.println(attendence1);                   

                        Double att1Tfinal = ((attendence1/15.0)*100.0);
                        System.out.println("sub1T"+att1Tfinal);
                        if (att1Tfinal>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }                                                                          
                                              
                    }
                }
              
                else if(subjectid.equals("ICT1123")){
                    String sub2 ="Select attendance from attendance_2023_ICT1123 where s_id='"+user+"' ";
                    ResultSet res2 = db.stm.executeQuery(sub2);
                    double attendence2=0;
                    
                    while(res2.next()){
                        Double att2 = res2.getDouble("attendance");

                        Double att2final = ((att2/15.0)*100.0);
                        System.out.println("sub1T"+att2final);
                        String s2 = String.format("%.2f%%",att2final);
                        if (att2final>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }
                       
                    }
                }
                else if(subjectid.equals("ICT1133")){
                    String sub3="Select attendance from attendance_2023_ICT1133 where s_id='"+user+"' AND type='Theory'OR 'Practical'";
                    ResultSet res3 = db.stm.executeQuery(sub3);
                    while(res3.next()){
                        Double att3 = res3.getDouble("attendance");

                        Double att3final = ((att3/15.0)*100.0);
                        System.out.println("sub1T"+att3final);
                        if (att3final>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }                                           
                    }
                }

                else if(subjectid.equals("ICT1143")){
                    String sub4="Select attendance from attendance_2023_ICT1143 where s_id='"+user+"' AND type='Practical' OR 'Theory'";
                    ResultSet res4 = db.stm.executeQuery(sub4);
                    while(res4.next()){
                        Double att4 = res4.getDouble("attendance");

                        Double att4final = ((att4/15.0)*100.0);
                        System.out.println("sub1T"+att4final);
                        if (att4final>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }    
                        
                        //String s4 = String.format("%.2f%%",att4final);
                        //jLabel5.setText(s3P);
                    }
                }

                else if(subjectid.equals("ENG1114")){
                    String sub5="Select attendance from attendance_2023_ENG1114 where s_id='"+user+"'";
                    ResultSet res5 = db.stm.executeQuery(sub5);
                    double atte5=0;
                    
                    while(res5.next()){
                        Double att5 = res5.getDouble("attendance");

                        Double att5final = ((att5/15.0)*100.0);
                        System.out.println("sub1T"+att5final);
                        String s5 = String.format("%.2f%%",att5final);
                        if (att5final>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }    
                        //jLabel5.setText(s4T);
                    }
                }

                else if(subjectid.equals("TMS1113")){
                    String sub6="Select attendance from attendance_2023_TMS1113 where s_id='"+user+"'";
                    ResultSet res6 = db.stm.executeQuery(sub6);
                    while(res6.next()){
                        Double att6 = res6.getDouble("attendance");

                        Double att6final = ((att6/15.0)*100.0);
                        System.out.println("sub1T"+att6final);
                        String s6 = String.format("%.2f%%",att6final);
                        if (att6final>80.0){
                            finalout.setText("ELIGIBLE");
                        }
                        else{
                            finalout.setText("NOT ELIGIBLE");
                        }    
                        //jLabel5.setText(s4P);
                    }
                }
                else {
                    Failed_Alert failed = new Failed_Alert();
                    failed.show();

                }

            } catch (Exception e) {
                //Failed_Alert failed = new Failed_Alert();
                //failed.show();
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void subidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturer_see_eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturer_see_eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturer_see_eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturer_see_eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturer_see_eligibility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField subid;
    // End of variables declaration//GEN-END:variables
}
