/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Student;

/**
 *
 * @author Hiru
 */
public class UpdateProfile extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProfile
     */
    public UpdateProfile() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        updateProfileLBL = new javax.swing.JLabel();
        idLBL = new javax.swing.JLabel();
        idTXT = new javax.swing.JTextField();
        emailLBL = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        updateEmailLBL = new javax.swing.JLabel();
        updateEmailTXT = new javax.swing.JTextField();
        updatePhoneLBL = new javax.swing.JLabel();
        updatePhoneTXT = new javax.swing.JTextField();
        proPicLBL = new javax.swing.JLabel();
        chooseFileBTN = new javax.swing.JButton();
        bgImgLBL = new javax.swing.JLabel();
        updateBTN = new javax.swing.JButton();
        backLBL = new javax.swing.JLabel();
        proPicIconLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateProfileLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        updateProfileLBL.setText("Update Profile");
        jPanel1.add(updateProfileLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 61, -1, -1));

        idLBL.setBackground(new java.awt.Color(255, 255, 255));
        idLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        idLBL.setForeground(new java.awt.Color(153, 153, 153));
        idLBL.setText("ID Number");
        jPanel1.add(idLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 173, -1, -1));

        idTXT.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        idTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTXTActionPerformed(evt);
            }
        });
        jPanel1.add(idTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 204, 396, 29));

        emailLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        emailLBL.setForeground(new java.awt.Color(153, 153, 153));
        emailLBL.setText("Email");
        jPanel1.add(emailLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 245, -1, -1));

        emailTXT.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        emailTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTXTActionPerformed(evt);
            }
        });
        jPanel1.add(emailTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 276, 396, 29));

        updateEmailLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        updateEmailLBL.setForeground(new java.awt.Color(153, 153, 153));
        updateEmailLBL.setText("Update Email To");
        jPanel1.add(updateEmailLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 317, -1, -1));

        updateEmailTXT.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        updateEmailTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmailTXTActionPerformed(evt);
            }
        });
        jPanel1.add(updateEmailTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 348, 396, 29));

        updatePhoneLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        updatePhoneLBL.setForeground(new java.awt.Color(153, 153, 153));
        updatePhoneLBL.setText("Update Phone Number To");
        jPanel1.add(updatePhoneLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 389, -1, -1));

        updatePhoneTXT.setFont(new java.awt.Font("Iskoola Pota", 1, 14)); // NOI18N
        updatePhoneTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneTXTActionPerformed(evt);
            }
        });
        jPanel1.add(updatePhoneTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 420, 396, 29));

        proPicLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        proPicLBL.setForeground(new java.awt.Color(153, 153, 153));
        proPicLBL.setText("Profile Picture");
        jPanel1.add(proPicLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 461, -1, -1));

        chooseFileBTN.setBackground(new java.awt.Color(245, 245, 245));
        chooseFileBTN.setFont(new java.awt.Font("Iskoola Pota", 1, 15)); // NOI18N
        chooseFileBTN.setText("Choose File");
        chooseFileBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chooseFileBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileBTNActionPerformed(evt);
            }
        });
        jPanel1.add(chooseFileBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 492, -1, 35));

        bgImgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update-profile.png"))); // NOI18N
        jPanel1.add(bgImgLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 122, 478, 479));

        updateBTN.setBackground(new java.awt.Color(76, 159, 255));
        updateBTN.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(255, 255, 255));
        updateBTN.setText("Update");
        updateBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(updateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 563, 396, -1));

        backLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Go Back.png"))); // NOI18N
        backLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBLMouseClicked(evt);
            }
        });
        jPanel1.add(backLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 90, 80));

        proPicIconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Account.png"))); // NOI18N
        jPanel1.add(proPicIconLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 461, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTXTActionPerformed
       String mail = emailTXT.getText();
    }//GEN-LAST:event_emailTXTActionPerformed

    private void chooseFileBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseFileBTNActionPerformed

    private void backLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBLMouseClicked
        Dashboard updateDb = new Dashboard();
        updateDb.show();
        dispose();
    }//GEN-LAST:event_backLBLMouseClicked

    private void idTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTXTActionPerformed
        String id = idTXT.getText();      
    }//GEN-LAST:event_idTXTActionPerformed

    private void updateEmailTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmailTXTActionPerformed
        String uMail = updateEmailTXT.getText();
    }//GEN-LAST:event_updateEmailTXTActionPerformed

    private void updatePhoneTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneTXTActionPerformed
        String phone = updatePhoneTXT.getText();
    }//GEN-LAST:event_updatePhoneTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLBL;
    private javax.swing.JLabel bgImgLBL;
    private javax.swing.JButton chooseFileBTN;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTXT;
    private javax.swing.JLabel idLBL;
    private javax.swing.JTextField idTXT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel proPicIconLBL;
    private javax.swing.JLabel proPicLBL;
    private javax.swing.JButton updateBTN;
    private javax.swing.JLabel updateEmailLBL;
    private javax.swing.JTextField updateEmailTXT;
    private javax.swing.JLabel updatePhoneLBL;
    private javax.swing.JTextField updatePhoneTXT;
    private javax.swing.JLabel updateProfileLBL;
    // End of variables declaration//GEN-END:variables
}
