
package Student;


/**
 *
 * @author Hiru
 */
public class UserProfile extends javax.swing.JFrame {

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backLBL = new javax.swing.JLabel();
        bgImgLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updateProPNL = new javax.swing.JPanel();
        userprofileIconLBL = new javax.swing.JLabel();
        idnoLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        genderLBL = new javax.swing.JLabel();
        levelLBL = new javax.swing.JLabel();
        updateproBTN = new javax.swing.JButton();
        idnotxtLBL = new javax.swing.JLabel();
        nametxtLBL = new javax.swing.JLabel();
        emailtxtLBL = new javax.swing.JLabel();
        phonetxtLBL = new javax.swing.JLabel();
        gendertxtLBL = new javax.swing.JLabel();
        leveltxtLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 750));

        backLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Go Back.png"))); // NOI18N
        backLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBLMouseClicked(evt);
            }
        });

        bgImgLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-profile.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        jLabel1.setText("User Profile");

        updateProPNL.setBackground(new java.awt.Color(245, 245, 245));

        userprofileIconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Male User.png"))); // NOI18N

        idnoLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        idnoLBL.setForeground(new java.awt.Color(153, 153, 153));
        idnoLBL.setText("ID Number");

        nameLBL.setBackground(new java.awt.Color(208, 208, 208));
        nameLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        nameLBL.setForeground(new java.awt.Color(153, 153, 153));
        nameLBL.setText("Name");

        emailLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        emailLBL.setForeground(new java.awt.Color(153, 153, 153));
        emailLBL.setText("Email");

        phoneLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        phoneLBL.setForeground(new java.awt.Color(153, 153, 153));
        phoneLBL.setText("Phone No");

        genderLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        genderLBL.setForeground(new java.awt.Color(153, 153, 153));
        genderLBL.setText("Gender");

        levelLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 20)); // NOI18N
        levelLBL.setForeground(new java.awt.Color(153, 153, 153));
        levelLBL.setText("Level");

        updateproBTN.setBackground(new java.awt.Color(76, 159, 255));
        updateproBTN.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        updateproBTN.setForeground(new java.awt.Color(255, 255, 255));
        updateproBTN.setText("Update Profile");
        updateproBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateproBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateproBTNActionPerformed(evt);
            }
        });

        idnotxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        idnotxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        idnotxtLBL.setOpaque(true);
        idnotxtLBL.setPreferredSize(new java.awt.Dimension(37, 25));

        nametxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        nametxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        nametxtLBL.setOpaque(true);
        nametxtLBL.setPreferredSize(new java.awt.Dimension(37, 25));

        emailtxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        emailtxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        emailtxtLBL.setOpaque(true);
        emailtxtLBL.setPreferredSize(new java.awt.Dimension(100, 25));

        phonetxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        phonetxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        phonetxtLBL.setToolTipText("");
        phonetxtLBL.setOpaque(true);
        phonetxtLBL.setPreferredSize(new java.awt.Dimension(238, 25));

        gendertxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        gendertxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        gendertxtLBL.setToolTipText("");
        gendertxtLBL.setOpaque(true);
        gendertxtLBL.setPreferredSize(new java.awt.Dimension(37, 25));

        leveltxtLBL.setBackground(new java.awt.Color(255, 255, 255));
        leveltxtLBL.setFont(new java.awt.Font("Iskoola Pota", 1, 16)); // NOI18N
        leveltxtLBL.setToolTipText("");
        leveltxtLBL.setOpaque(true);
        leveltxtLBL.setPreferredSize(new java.awt.Dimension(238, 25));

        javax.swing.GroupLayout updateProPNLLayout = new javax.swing.GroupLayout(updateProPNL);
        updateProPNL.setLayout(updateProPNLLayout);
        updateProPNLLayout.setHorizontalGroup(
            updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProPNLLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateproBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(updateProPNLLayout.createSequentialGroup()
                        .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idnoLBL)
                            .addComponent(nameLBL)
                            .addComponent(emailLBL)
                            .addComponent(phoneLBL)
                            .addComponent(genderLBL)
                            .addComponent(levelLBL))
                        .addGap(38, 38, 38)
                        .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idnotxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nametxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailtxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phonetxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gendertxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leveltxtLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateProPNLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userprofileIconLBL)
                .addGap(220, 220, 220))
        );
        updateProPNLLayout.setVerticalGroup(
            updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateProPNLLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(userprofileIconLBL)
                .addGap(18, 18, 18)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idnoLBL)
                    .addComponent(idnotxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLBL)
                    .addComponent(nametxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLBL)
                    .addComponent(emailtxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLBL)
                    .addComponent(phonetxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLBL)
                    .addComponent(gendertxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(updateProPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLBL)
                    .addComponent(leveltxtLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(updateproBTN)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLBL)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addComponent(bgImgLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addComponent(updateProPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backLBL)
                                .addGap(26, 26, 26)))
                        .addGap(32, 32, 32)
                        .addComponent(bgImgLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(updateProPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void backLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBLMouseClicked
        Dashboard userDb = new Dashboard(username);
        userDb.show();
        dispose();
    }//GEN-LAST:event_backLBLMouseClicked

    private void updateproBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateproBTNActionPerformed
       UpdateProfile update = new UpdateProfile();
       update.show();
       dispose();
    }//GEN-LAST:event_updateproBTNActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//       
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLBL;
    private javax.swing.JLabel bgImgLBL;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JLabel emailtxtLBL;
    private javax.swing.JLabel genderLBL;
    private javax.swing.JLabel gendertxtLBL;
    private javax.swing.JLabel idnoLBL;
    private javax.swing.JLabel idnotxtLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel levelLBL;
    private javax.swing.JLabel leveltxtLBL;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JLabel nametxtLBL;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JLabel phonetxtLBL;
    private javax.swing.JPanel updateProPNL;
    private javax.swing.JButton updateproBTN;
    private javax.swing.JLabel userprofileIconLBL;
    // End of variables declaration//GEN-END:variables
}